FROM python:3.11-slim

WORKDIR /usr/src/bot

# Установка зависимостей
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Копируем код бота
COPY telegram_bot/ .