# Generated by Django 5.2.7 on 2025-10-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personal_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен личного бота'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_bot_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username личного бота'),
        ),
    ]
