# Generated by Django 5.2.10 on 2026-01-20 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_login_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Токен входа Telegram',
                'verbose_name_plural': 'Токены входа Telegram',
                'indexes': [models.Index(fields=['token'], name='users_teleg_token_1e1c74_idx'), models.Index(fields=['expires_at'], name='users_teleg_expires_0ef5c7_idx')],
            },
        ),
    ]
