# Generated by Django 5.2.7 on 2025-10-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', '-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='teamlist',
            options={'verbose_name': 'Список команды', 'verbose_name_plural': 'Списки команд'},
        ),
    ]
