# Generated by Django 5.2.7 on 2025-10-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_alter_teamlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', '-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='teamlist',
            options={'verbose_name': 'Team List', 'verbose_name_plural': 'Team Lists'},
        ),
    ]
