# Generated by Django 5.2.10 on 2026-01-17 10:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_options_alter_teamlist_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', '-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='teamlist',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='teamlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='teamlist',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок (дедлайн)'),
        ),
        migrations.AddField(
            model_name='teamlist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание / ТЗ'),
        ),
        migrations.AddField(
            model_name='teamlist',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Общая стоимость проекта (позже добавим финансы детальнее).', max_digits=12, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='teamlist',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='teamlist',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата старта'),
        ),
        migrations.AddField(
            model_name='teamlist',
            name='status',
            field=models.CharField(choices=[('negotiation', 'Переписка'), ('development', 'В разработке'), ('rejected', 'Не принят'), ('done', 'Завершён')], default='negotiation', max_length=32, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='teamlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.teamlist', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='teamlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_lists', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='teamlist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
