# Generated by Django 5.2.10 on 2026-01-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_options_alter_teamlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlist',
            name='source',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('website', 'Сайт'), ('recommendation', 'Рекомендация'), ('returning', 'Повторный клиент'), ('other', 'Другое')], max_length=32, null=True, verbose_name='Источник'),
        ),
    ]
