# Generated by Django 5.2.10 on 2026-01-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('tasks', '0006_teamlist_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockedScheduleRu',
            fields=[
            ],
            options={
                'verbose_name': 'Время',
                'verbose_name_plural': 'Время',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.clockedschedule',),
        ),
        migrations.CreateModel(
            name='CrontabScheduleRu',
            fields=[
            ],
            options={
                'verbose_name': 'Crontab',
                'verbose_name_plural': 'Crontab',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.crontabschedule',),
        ),
        migrations.CreateModel(
            name='IntervalScheduleRu',
            fields=[
            ],
            options={
                'verbose_name': 'Интервал',
                'verbose_name_plural': 'Интервалы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.intervalschedule',),
        ),
        migrations.CreateModel(
            name='PeriodicTaskRu',
            fields=[
            ],
            options={
                'verbose_name': 'Периодическая задача',
                'verbose_name_plural': 'Периодические задачи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.periodictask',),
        ),
        migrations.CreateModel(
            name='SolarScheduleRu',
            fields=[
            ],
            options={
                'verbose_name': 'Астрономическое событие',
                'verbose_name_plural': 'Астрономические события',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.solarschedule',),
        ),
    ]
