# Generated by Django 5.2.10 on 2026-01-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_clockedscheduleru_crontabscheduleru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crontabscheduleru',
            options={'verbose_name': 'Расписание (cron)', 'verbose_name_plural': 'Расписания (cron)'},
        ),
    ]
