# Generated by ChatGPT on 2026-02-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_teamlist_options_task_actual_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создана'), ('updated', 'Обновлена'), ('status_changed', 'Статус изменён'), ('completed', 'Завершена'), ('uncompleted', 'Возвращена в работу'), ('commented', 'Комментарий')], max_length=32, verbose_name='Действие')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_audit_logs', to='users.user', verbose_name='Пользователь')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Аудит задачи',
                'verbose_name_plural': 'Аудит задач',
                'ordering': ('-created_at',),
            },
        ),
    ]
