# Generated by ChatGPT on 2026-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_taskauditlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='task_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='task_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['list'], name='task_list_idx'),
        ),
    ]
