"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import dj_database_url # Импорт для парсинга DATABASE_URL

# --- НОВОЕ: Загружаем переменные окружения из .env файла ---
load_dotenv()
# -------------------------------------------------------------

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# --- НОВОЕ: Проверка SECRET_KEY в режиме продакшена ---
if not SECRET_KEY and not DEBUG:
    raise EnvironmentError("SECRET_KEY must be set in a non-DEBUG environment (production).")
# --------------------------------------------------------

# settings.py
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'channels',
    'django_celery_beat',
    'crispy_forms',
    'corsheaders', 
    # Local apps
    'users',
    'tasks',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # ДОЛЖЕН БЫТЬ ПЕРВЫМ
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# --- КОРРЕКТНАЯ КОНФИГУРАЦИЯ ДЛЯ RENDER / POSTGRESQL ---
DATABASES = {
    'default': dj_database_url.config(
        # Читает DATABASE_URL из переменной окружения
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600, # Максимальное время жизни соединения
        conn_health_checks=True,
    )
}
# ---------------------------------------------------------

# Channels (Websockets)
ASGI_APPLICATION = 'core.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # Оставляем хардкод 'redis' для работы в Docker-сети
            "hosts": [("redis", 6379)], 
        },
    },
}

# Celery
# Оставляем хардкод 'redis' для работы в Docker-сети
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_BEAT_SCHEDULE = {
    'check-deadlines-every-5-minutes': {
        'task': 'tasks.tasks.check_deadlines', # Путь к задаче
        'schedule': timedelta(minutes=5),
    },
}
# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication', # Для Frontend
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static', # Если вы хотите использовать app/static/
]
STATIC_ROOT = BASE_DIR / 'static_files' 
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'


# --- НОВЫЙ БЛОК: CORS & Credentials Configuration ---
# Позволяет загружать список разрешенных доменов из переменной окружения,
# разделенных запятыми, с запасными значениями для локальной разработки.
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in 
    os.environ.get(
        'CORS_ALLOWED_ORIGINS', 
        'http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000'
    ).split(',')
]

# Обычно необходимо, чтобы фронтенд мог отправлять куки (credentials)
CORS_ALLOW_CREDENTIALS = True
# ----------------------------------------------------


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4" # или 'bootstrap5', если вы используете его
CRISPY_TEMPLATE_PACK = "bootstrap4" 


# --- УЛУЧШЕННЫЙ БЛОК: Настройки безопасности для Prod/Dev ---
if not DEBUG:
    # Production Security Settings (HTTPS Enforced)
    
    # 1. Принудительный редирект на HTTPS
    SECURE_SSL_REDIRECT = True
    
    # 2. Обеспечение безопасных куки
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # 3. HSTS (HTTP Strict Transport Security) - критично для продакшена
    # Заставляет браузеры всегда использовать HTTPS в течение года
    SECURE_HSTS_SECONDS = 31536000 # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # 4. Указывает, что прокси-серверы (Render, Nginx) являются доверенными
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # 5. Дополнительные заголовки безопасности
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

else:
    # Development Settings (Allow HTTP for local use)
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_PROXY_SSL_HEADER = None

# Всегда используйте DENY для защиты от кликджекинга
X_FRAME_OPTIONS = 'DENY'